name: ecoplaycaicara
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.3
  provider: ^6.1.1
  form_field_validator: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
  - lib/assets/images/
  - lib/assets/avatares/
  - lib/assets/cards/
  - lib/assets/games/toca-do-caranguejo/background.png
  - lib/assets/games/toca-do-caranguejo/caranguejo.png
